version: "3.8"

services:
  logging_app:
    build:
      context: .
    ports:
      - "8501:8501"  # Map the container's Streamlit default port to host port 8501
    volumes:
      - /DATA/Documents/secrets.toml:/app/.streamlit/secrets.toml
    command: ["streamlit", "run", "shooting_logging/app.py"]

  statistics_app:
    build:
      context: .
    ports:
      - "8502:8501"  # Map the container's Streamlit default port to host port 8502
    volumes:
      - /DATA/Documents/secrets.toml:/app/.streamlit/secrets.toml
    command: ["streamlit", "run", "shooting_statistics/app.py"]
